!function(d,f,g){function m(b){var c=n.className,a=e._config.classPrefix||"";if(r&&(c=c.baseVal),e._config.enableJSClass)c=c.replace(new RegExp("(^|\\s)"+a+"no-js(\\s|$)"),"$1"+a+"js$2");e._config.enableClasses&&(c+=" "+a+b.join(" "+a),r?n.className.baseVal=c:n.className=c)}function l(b,c){if("object"==typeof b)for(var a in b)p(b,a)&&l(a,b[a]);else{b=b.toLowerCase();a=b.split(".");var d=e[a[0]];if(2==a.length&&(d=d[a[1]]),"undefined"!=typeof d)return e;c="function"==typeof c?c():c;1==a.length?e[a[0]]=
c:(!e[a[0]]||e[a[0]]instanceof Boolean||(e[a[0]]=new Boolean(e[a[0]])),e[a[0]][a[1]]=c);m([(c&&0!=c?"":"no-")+a.join("-")]);e._trigger(b,c)}return e}var q=[],k=[],h={_version:"3.3.1",_config:{classPrefix:"",enableClasses:!0,enableJSClass:!0,usePrefixes:!0},_q:[],on:function(b,c){var a=this;setTimeout(function(){c(a[b])},0)},addTest:function(b,c,a){k.push({name:b,fn:c,options:a})},addAsyncTest:function(b){k.push({name:null,fn:b})}},e=function(){};e.prototype=h;var e=new e,p,n=f.documentElement,r="svg"===
n.nodeName.toLowerCase();!function(){var b={}.hasOwnProperty;p="undefined"===typeof b||"undefined"===typeof b.call?function(c,a){return a in c&&"undefined"===typeof c.constructor.prototype[a]}:function(c,a){return b.call(c,a)}}();h._l={};h.on=function(b,c){this._l[b]||(this._l[b]=[]);this._l[b].push(c);e.hasOwnProperty(b)&&setTimeout(function(){e._trigger(b,e[b])},0)};h._trigger=function(b,c){if(this._l[b]){var a=this._l[b];setTimeout(function(){var b;for(b=0;b<a.length;b++)(0,a[b])(c)},0);delete this._l[b]}};
e._q.push(function(){h.addTest=l});e.addAsyncTest(function(){function b(c,b,a){function e(b){var e=b&&"load"===b.type?1==d.width:!1;l(c,"webp"===c?new Boolean(e):e);a&&a(b)}var d=new Image;d.onerror=e;d.onload=e;d.src=b}var c=[{uri:"data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoBAAEAAwA0JaQAA3AA/vuUAAA=",name:"webp"},{uri:"data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAABBxAR/Q9ERP8DAABWUDggGAAAADABAJ0BKgEAAQADADQlpAADcAD++/1QAA==",name:"webp.alpha"},{uri:"data:image/webp;base64,UklGRlIAAABXRUJQVlA4WAoAAAASAAAAAAAAAAAAQU5JTQYAAAD/////AABBTk1GJgAAAAAAAAAAAAAAAAAAAGQAAABWUDhMDQAAAC8AAAAQBxAREYiI/gcA",
name:"webp.animation"},{uri:"data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=",name:"webp.lossless"}],a=c.shift();b(a.name,a.uri,function(a){if(a&&"load"===a.type)for(a=0;a<c.length;a++)b(c[a].name,c[a].uri)})});(function(){var b,c,a,d,f,g;for(g in k)if(k.hasOwnProperty(g)){if(b=[],c=k[g],c.name&&(b.push(c.name.toLowerCase()),c.options&&c.options.aliases&&c.options.aliases.length))for(a=0;a<c.options.aliases.length;a++)b.push(c.options.aliases[a].toLowerCase());a="function"===
typeof c.fn?c.fn():c.fn;for(d=0;d<b.length;d++)f=b[d],f=f.split("."),1===f.length?e[f[0]]=a:(!e[f[0]]||e[f[0]]instanceof Boolean||(e[f[0]]=new Boolean(e[f[0]])),e[f[0]][f[1]]=a),q.push((a?"":"no-")+f.join("-"))}})();m(q);delete h.addTest;delete h.addAsyncTest;for(f=0;f<e._q.length;f++)e._q[f]();d.Modernizr=e}(window,document);
function getScrollTop(){var d;"number"==typeof window.pageYOffset?d=window.pageYOffset:document.body&&document.body.scrollTop?d=document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop&&(d=document.documentElement.scrollTop);return d}function navMove(){300<getScrollTop()?document.getElementById("sidebar").className="nav__list--fixed":document.getElementById("sidebar").className="nav__list"}
function navHighlight(){var d=document.body.getElementsByTagName("h3"),f=[];for(i=0;i<d.length;i++)f[i]=d[i].offsetTop-200;f.push(99999999);var d=document.getElementById("navIntro"),g=document.getElementById("navToolkit"),m=document.getElementById("navResponsiveness"),l=document.getElementById("navCompression"),q=document.getElementById("navDesign"),k=document.getElementById("navCaching"),h=document.getElementById("navCssOptimizations"),e=document.getElementById("navImageOptimizations"),p=document.getElementById("navInTheWorks"),
d=[d,g,m,l,q,k,h,e,p];for(i=g=0;i<f.length;i++)if(g+=1,getScrollTop()>f[i]&&getScrollTop()<f[i+1]){for(i=0;i<d.length;i++)d[i].className="nav__item";d[g-1].className="nav__item--active"}}function navStop(){var d=document.body.clientHeight,f=document.getElementById("sidebar").clientHeight;d-160<getScrollTop()+67+f&&(document.getElementById("sidebar").className="nav__list--bottom")}
function setHeaderBgs(){function d(d,f){var g=new Image;g.onload=f;g.src=d}var f=document.getElementById("header"),g=document.getElementById("title-bg");window.matchMedia("(min-resolution: 3dppx),(-webkit-min-device-pixel-ratio: 3)").matches?html.classList.contains("webp")?window.matchMedia("(max-width: 540px)").matches?d("images/floral-crop-540w-3x.webp",function(){f.className="header--webp-3x";g.className="title-bg--webp-3x"}):d("images/floral-crop-2x.webp",function(){f.className="header--webp-2x";
g.className="title-bg--webp-2x"}):window.matchMedia("(max-width: 540px)").matches?d("images/floral-crop-540w-3x.png",function(){f.className="header--png-3x";g.className="title-bg--png-3x"}):d("images/floral-crop-2x.png",function(){f.className="header--png-2x";g.className="title-bg--png-2x"}):window.matchMedia("(min-resolution: 2dppx),(-webkit-min-device-pixel-ratio: 2)").matches&&(html.classList.contains("webp")?window.matchMedia("(max-width: 540px)").matches?d("images/floral-crop-540w-2x.webp",function(){f.className=
"header--webp-2x";g.className="title-bg--webp-2x"}):d("images/floral-crop-2x.webp",function(){f.className="header--webp-2x";g.className="title-bg--webp-2x"}):window.matchMedia("(max-width: 540px)").matches?d("images/floral-crop-540w-2x.png",function(){f.className="header--png-2x";g.className="title-bg--png-2x"}):d("images/floral-crop-2x.png",function(){f.className="header--png-2x";g.className="title-bg--png-2x"}))}var page=document.body.dataset.pageName;
controller={scroll:function(){"design"===page?(navMove(),navHighlight(),navStop()):"resume"===page&&(navMove(),navStop())},load:function(){"design"===page?(navMove(),navHighlight(),setHeaderBgs(),navStop()):"resume"===page&&(navMove(),setHeaderBgs(),navStop())}};window.onscroll=controller.scroll;window.onload=controller.load;